# Generated by Django 5.0.2 on 2024-03-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcomment',
            options={'ordering': ('-created_at',)},
        ),
    ]
