# Generated by Django 5.0.2 on 2024-03-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('massage_masters', '0005_massagemaster_master_foto'),
        ('massage_types', '0002_massagetype_current_status_massagetype_massage_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('client_phone', models.CharField()),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('session_status', models.CharField(default='processing')),
                ('session_comment', models.TextField(blank=True, max_length=200, null=True)),
                ('session_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='massage_masters.massagemaster')),
                ('session_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='massage_types.massagetype')),
            ],
        ),
    ]
