# Generated by Django 5.0.3 on 2024-03-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagesession',
            name='session_status',
            field=models.CharField(choices=[('done', 'done'), ('processing', 'processing'), ('scheduled', 'scheduled'), ('canceled', 'canceled')], default='processing'),
        ),
    ]
