# Generated by Django 5.0.2 on 2024-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagetype',
            name='current_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='massagetype',
            name='massage_cover',
            field=models.ImageField(blank=True, null=True, upload_to='types/'),
        ),
    ]
