# Generated by Django 5.0.2 on 2024-02-11 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massagemaster',
            name='master_rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
