# Generated by Django 5.0.2 on 2024-02-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_masters', '0002_alter_massagemaster_master_rating'),
        ('massage_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='massage_masters.massagemaster')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='massage_types.massagetype')),
            ],
        ),
        migrations.AddField(
            model_name='massagemaster',
            name='master_types',
            field=models.ManyToManyField(related_name='types', through='massage_masters.MasterTypes', to='massage_types.massagetype'),
        ),
    ]
