# Generated by Django 5.0.2 on 2024-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage_masters', '0004_rename_mastertypes_mastertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='massagemaster',
            name='master_foto',
            field=models.ImageField(blank=True, null=True, upload_to='masters/'),
        ),
    ]
