# Generated by Django 5.0.3 on 2024-03-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage_masters', '0005_massagemaster_master_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massagemaster',
            options={'ordering': ('last_name',)},
        ),
    ]
